name: apl_ml_course
channels:
  - conda-forge
  - defaults
dependencies:
  - umap-learn=0.3.2
  - ipywidgets=7.4.0
  - jupyterlab=0.33.8
  - pandas=0.23.4
  - plotly=3.1.0
  - python=3.6.6
  - scikit-learn=0.19.1
  - scipy=1.1.0
  - seaborn=0.9.0

